### PR TITLE
Designer

### PR DESCRIPTION
**Pull request by jsvdvis**
Not bug-free, please tell me if you find bugs/weird behaviour

### CODE REVIEW

**Review by gizemayydin — APPROVED** [review]

**Comment by Dansuf** [comment]
I didn't find any bigger issues, however I didn't look closely at the vue code.

I'd recommend solving merge conflicts by a merge rather than by creating a commit.

**Comment by jsvdvis** [comment]
I solved the conflicts by merging development with designer, then fixing the merge conflicts, of that's what you mean.

**Comment by Dansuf** [comment]
I mean that if a pull request is approved, you can do a standard `git merge` from designer to development on your local repository, resolve conflicts and then push. However, the instructions on github seem to say something different.

**Comment by Dansuf** [comment]
I found one issue with the designer. When you provide some data to the result step and click apply, you get a warning on the top. However, it disappears too quickly to read the whole message.

**Comment by jsvdvis** [comment]
Oh seriously, I did not know, I'll use that method for later conflicts then. I'll also increase the time the messages are shown, you are right in that the messages disappear too fast.

**Pull request merged**
