### PR TITLE
Accounts

### PR DESCRIPTION
**Pull request by Dansuf**
Expanded registration form with new variables and improved the looks; added e-mail verification of users; added administrator verification of users; added various permissions for accessing subpages and database models.

This PR contains some merged changes from the designer branch, I believe that they don't break anything, but that should be probably checked.

### CODE REVIEW

**Review by jsvdvis — APPROVED** [review]
Your code looks good, I've tested the mailserver thing (is going to be a problem for TA's...), works nicely. Does the uploading work?

**Comment by Dansuf** [comment]
Thanks for the review. The TA's can probably test the website on the server we set up. I'll configure e-mail server there. Uploading of files should work. Did it not work for you?

**Comment by jsvdvis** [comment]
I forgot to test it, to be honest. Is there a reason for the three upload
forms btw?

**Comment by Dansuf** [comment]
Yeah, the number should be probably limited to one or two.

**Pull request merged**
